[meta]
title="Similarity Search on Vector Data"
description="Example of similarity searches over vector data."
tags=["starter", "openai", "genai", "vectordb"]
destinations=["spaces"]
icon="vector-circle"
minimum_tier="free-shared"
